### ISSUE TITLE
If condition to show up item in case it is true

### ISSUE THREAD

**Issue by nandrianaivojaona** [maternite/freemedforms#14]
In many forms like gyneco, the choice of a specific answer  would not show others protocols (transcripted to items in XML language) during the consultation. How to insert an if-case in freedmedfroms ?

**Comment by jeromecc** [comment]
Je crois que tu as trouvé la solution. :-) En écrivant des formulaires dynamiques complexes avec du code JavaScript. Ce qui risque de complexifier énormément le travail et de retarder la mise en production, pour un gain modeste en terme de confort d'utilisation.
