### ISSUE TITLE
Button to click to validate that all checkings are normal

### ISSUE THREAD

**Issue by nandrianaivojaona** [maternite/freemedforms#15]
Wishes to get a button or a checked box to ensure that all protocols for a standard checking are in normal condition. In checking or clicking so, the values to attribute to all protocols would be "normal", and the all items related to would be not shown up.

**Comment by jeromecc** [comment]
Un des plus gros progrès en terme de sécurité dans les processus hospitaliers est apparu très récemment dans le monde médical (alors que c'est utilisé depuis longtemps dans l'industrie, l'aéronautique ou le sport automobile): la checklist.
Tu peux lire la page de l'Organisation Mondiale pour la Santé sur la checklist: http://www.who.int/patientsafety/implementation/checklists/background/en/ qui cite les travaux du Professeur Atul Gawande de la Harvard School of Public Health. Il a écrit "The Checlist Manifesto".

Le principe d'une checklist est que le soignant lit les items et les coche au fur et à mesure.
Lire les items lui permet d'y penser.

Si tu crée un bouton qui permet de cocher automatiquement tous les items d'une checklist, tu retires complètement l'avantage de la checklist.

Et au niveau de la justice: un incident survient pendant les soins et le patient porte plainte. Le juge se renseigne sur le fonctionnement du logiciel utilisé à l'hôpital et se rend compte qu'il suffit de cliquer sur un bouton pour que toutes les choses que le médecin doit vérifier pendant l'examen clinique soient enregistrées comme "normal". Ainsi tu annules aussi l'effet de preuve du dossier médical.

Créer un moyen automatique de remplir une checklist médicale annule tout le bénéfice de la checklist.

Je crois qu'il ne faut surtout pas faire ça.
